# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: feedback_dev
  username: root
  password: root 
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: feedback_test
  username: root
  password: root
  pool: 5
  timeout: 5000
